version: '3.7'

services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=${POSTGRES_DB}'
      - 'POSTGRES_PASSWORD=${POSTGRES_PASSWORD}'
      - 'POSTGRES_USER=${POSTGRES_USER}'
    ports:
      - '5432:5432'
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
  first-checkout:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - 'SPRING_DATASOURCE_URL=${DB_URL}'
      - 'SPRING_DATASOURCE_USERNAME=${POSTGRES_USER}'
      - 'SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}'
      - 'SPRING_JPA_HIBERNATE_DDL_AUTO=update'
    depends_on:
      postgres:
         condition: service_healthy
    ports:
      - '8080:8080'